# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 1
#
# Initialize kernel
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#/event/verbose 0
#/tracking/verbose 1
# 

# 
#
/gun/particle pi+
/gun/energy 0.1 GeV
#/run/verbose 2
#/tracking/verbose 1
#/process/verbose 2
#

/run/beamOn 100
